### ISSUE TITLE
What's the most efficient way to render a XAML visual tree onto a DXGI surface?

### ISSUE THREAD

**Issue by AdamSzofran** [microsoft/WindowsCompositionSamples#296] opened 2018-08-11 02:58 UTC
(I originally posted this question in the [Win2D](https://github.com/Microsoft/Win2D/issues/630) repo but this might be a more appropriate place for it.)

I'm using [`MediaCapture`](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-mediacapture) in a UWP app to get a video stream from a camera with the intent to simultaneously record it and live stream it. For sports, I'd like to overlay scoreboard information that I've laid out using XAML controls.

I plan to use either the [D3D11 video APIs](https://docs.microsoft.com/en-us/windows/desktop/medfound/direct3d-11-video-apis) or a [custom video effect](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/custom-video-effects) (and Win2D if applicable) to do the overlay in real-time. However, both of those techniques require the overlay to be in a DXGI surface and I can't figure out how to efficiently render the XAML tree into one. The best approach I've seen is to use [`RenderTargetBitmap`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.rendertargetbitmap) and then copy the bits to the CPU before pushing them back into DXGI. That seems horribly inefficient.

[`XamlUIPresenter`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.xamluipresenter) looks like it would be perfect but 
> XamlUIPresenter is not intended for general Microsoft DirectX and Windows Runtime interoperation scenarios. You cannot use this API in a UWP app that you submit to the Microsoft Store, it will not pass certification.

Is there a way to do this with supported APIs entirely in video memory without the round trip to the CPU?

Thanks.

**Comment by daneuber** [comment] 2018-08-14 17:26
Hi @AdamSzofran can you clarify whether you wanted the XAML scores overlay over BOTH the stream and recording or only one of them?

**Comment by AdamSzofran** [comment] 2018-08-14 19:17
Both streams. I have it working currently via `RenderTargetBitmap` to a SharpDX `Texture2D` through the CPU via `GetPixelsAsync`. Then into the video streams via `IBasicVideoEffect` with a `VideoProcessorBlt`.

Fortunately I only need to use the `RenderTargetBitmap` infrequently when the clock or score changes and even then I only have to update a small part of the overlay. Still, it would be nice to eliminate the path through the CPU because then I could use animations on the overlay that would update more frequently.

**Comment by AdamSzofran** [comment] 2018-08-14 22:44
It would be great if there was a way to get the DXGI surface backing the `RenderTargetBitmap` (presumably there is one). Then you could use it on the GPU with D3D, D2D, etc. without having to copy it back to the CPU. Thanks.

**Comment by daneuber** [comment] 2018-08-23 18:32
Thanks for the additional info @AdamSzofran! Given your scenario we'd suggest you build the UI using XAML, get the backing Visual (using [ElementCompositionPreview](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Hosting.ElementCompositionPreview)) for the root element of the subtree you'd like to capture, and then capture the content to a D3D surface using the [Capture API](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) -  `var item = GraphicsCaptureItem.CreateFromVisual(visual);` Let us know if that works for you!

**Comment by AdamSzofran** [comment] 2018-08-23 23:05
Thank you @daneuber! I will try that. For some reason I thought the capture API required the user to select the visual manually and give permission but perhaps that's not required when capturing a `Visual` from your own app.

**Comment by kannan95** [comment] 2018-09-25 13:14
Hi @daneuber @AdamSzofran , I am trying to build a screen capture UWP app to capture the whole display(Full screen). I don't need to provide a picker to the user to choose since I need to capture whole display always. The [Capture API](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) can be used to capture screen but it needs a picker to work. 
How can I capture the whole screen using Capture API without a picker? If `GraphicsCaptureItem.CreateFromVisual `can be use to do that, how? Thanks in advance.

**Comment by daneuber** [comment] 2018-09-28 18:19
Hi @kannan95 as of now the picker is required as part of the capture API, but providing the option to opt out of the picker is a request we're tracking internally as something we may support in the future.

**Comment by kannan95** [comment] 2018-10-07 16:14
Thanks for the update @daneuber I'll definitely watch out for that.

**Comment by daneuber** [comment] 2018-10-30 21:49
@AdamSzofran Yes sorry for the delay; CreateFromVisual was a new feature recently added to the Capture APIs available in Insider build. Let us know how trying that out for your scenario goes!

**Comment by Adam-VisualVocal** [comment] 2018-10-30 21:55
Will do. I held off trying this while the feature was pre-release because I didn't have time to set up a VM to test it. Now that 17763 is out I plan to give it a go very soon. Thanks.

**Comment by AdamSzofran** [comment] 2019-12-01 16:53
I did finally get this working, mostly. The issue I'm having now is that the Xaml is always rendered onto an opaque black background and alpha is not preserved in the captured image. How can I capture transparent or semi-transparent Xaml and have the resulting captured image not be fully opaque? Thanks.

**Comment by Zofware** [comment] 2019-12-01 19:38
Looks like the transparency issue might be a bug: https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/41

**Comment by Zofware** [comment] 2020-06-21 07:27
I can confirm that the transparency issue is definitely fixed in Windows 10 build 19041 (aka May 2020, aka 2004). Yay!

**Closed** 2024-06-10 21:19 UTC
Labels: question, general-composition
