### ISSUE TITLE
Bug with LayerVisual in Preview 17123

### ISSUE THREAD

**Issue by devsko** [Microsoft/WindowsCompositionSamples#276] opened 2018-03-15 13:33 UTC
## Issue Type

[ x ] Bug Report   
[ ] Feature Request   
[ ] Sample request  
[ ] Documentation issue or request  
[ ] Other – Please describe:   

## Current Behavior
In current Insider Preview 17120 a LayerVisual which has both a DropShadow and a Effect (combined backdrop, blur, tint and composite with mask) and then gets moved around by changing Offset disappears and gets visible randomly

## Expected Behavior
The LayerVisual should always get rendered

## Steps to Reproduce (for bugs)
1. In VisualStudio create a new UWP app (target 16299) and add Win2D.uwp 1.21 package
2. Replace MainPage.xaml.cs with https://gist.github.com/devsko/671ecacc11c35d02bb925adaa6e66001

##  Your Environment
* SDK #:  17115
* Operating System build # :  17120
* Visual Studio Version # : 15.7 Preview 1

**Comment by devsko** [comment] 2018-03-17 00:53
Still exists in 17123

**Comment by sohchatt** [comment] 2018-03-17 00:58
Thanks for filing this issue; I reproduced this as well while answering your question about LayerVisual + Shadows. Leaving this issue open till it's fixed in a future Insider build.

**Comment by daneuber** [comment] 2018-10-31 00:33
@devsko Thanks for the feedback. This should be fixed as of SDK [17763](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk).

**Comment by likuba** [comment] 2018-12-05 00:07
Closing since this is fixed in the release build.  Please re-open if the issue if you are still seeing this repro in current builds.

**Closed by likuba** 2018-12-05 00:07 UTC
Labels: bug, effects
